services:
  rabbitmq:
    image: rabbitmq:3-management
    # ports:
    #   - '5672:5672'
    #   - '15672:15672'

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
    command: /bin/bash -c "bin/setup && bin/rails s -b 0.0.0.0 -p 3033"
    # ports:
    #   - 3033:3033
    depends_on:
      - rabbitmq
    environment:
      POLICYZINHA_SERVICE: 'http://policyzinha-service:3000'
#     networks:
#       policyzinha-service_default:
#         aliases:
#           - bff

# networks:
#   policyzinha-service_default:
#     external: true
