# syntax = docker/dockerfile:1

FROM ruby:3.3.0

WORKDIR /rails

ENV RAILS_ENV="development"

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git pkg-config

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives
