services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
    command: /bin/bash -c "bin/setup && bin/rails s -b 0.0.0.0 -p 3033"
    ports:
      - 3033:3033
    environment:
      POLICYZINHA_HOST: 'http://policyzinha-service:3030'
      RABBITMQ_HOST: amqp://guest:guest@rabbitmq:5672
#     networks:
#       policyzinha-service_default:
#         aliases:
#           - bff

# networks:
#   policyzinha-service_default:
#     external: true
